In [1]:
from numpy import array


def split_sequence(sequence,n_steps):
    x,y = list(), list()
    for i in range(len(sequence)):
        end_x  = i + n_steps

        # check if we are beyond the sequence
        if end_x > len(sequence)-1:
            break
        # gather input and output part
        seq_x, seq_y = sequence[i:end_x], sequence[end_x]
        x.append(seq_x)
        y.append(seq_y)
    return array(x), array(y)

series = array([1,2,3,4,5,6,7,8,9,10])
x,y = split_sequence(series,3)
for i in range(len(x)):
    print(x[i],y[i])

[1 2 3] 4
[2 3 4] 5
[3 4 5] 6
[4 5 6] 7
[5 6 7] 8
[6 7 8] 9
[7 8 9] 10


In [2]:

#transform univariate time series to supervised learning problem
from numpy import array
# split a univariate sequence into samples
def split_sequence(sequence, n_steps):
    X, y = list(), list()
    for i in range(len(sequence)):
        # find the end of this pattern
        end_ix = i + n_steps
        # check if we are beyond the sequence
        if end_ix > len(sequence)-1:
            break
        # gather input and output parts of the pattern
        seq_x, seq_y = sequence[i:end_ix], sequence[end_ix]
        X.append(seq_x)
        y.append(seq_y)

    return array(X), array(y)
# define univariate time series
series = array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(series.shape)
# transform to a supervised learning problem
X, y = split_sequence(series, 3)
print(X.shape, y.shape)
x = x.reshape(x.shape[0],x.shape[1],1)
print(x.shape)

(10,)
(7, 3) (7,)
(7, 3, 1)


# Consider that you are in the current situation:
I have two columns in my data file with 5,000 rows, column 1 is time (with 1 hour
interval) and column 2 is the number of sales and I am trying to forecast the number
of sales for future time steps. Help me to set the number of samples, time steps and
features in this data for an LSTM?

# We will work through this example, broken down into the following 4 steps:
1. Load the Data
2. Drop the Time Column
3. Split Into Samples
4. Reshape Subsequences

In [3]:
from numpy import array

data = list()
n = 5000
for i in range(n):
    data.append([(i+1),(i+1)*10])
data = array(data)
print(data[:5, :])
print(data.shape)

[[ 1 10]
 [ 2 20]
 [ 3 30]
 [ 4 40]
 [ 5 50]]
(5000, 2)


In [4]:
# drop the time column
data = list()
n = 5000
for i in range(n):
    data.append([(i+1), (1+1)*10])
data = array(data)
#drop the time column
data = data[:,1]
print(data.shape) 


# split our data in 200 time-steps (5000/25 = 200)
samples = list()
length = 200
for i in range(0,n,length):
    sample = data[i:i+length]
    samples.append(sample)
print(len(samples))


# converte our sample into 2D
data = array(samples)
print(data.shape)

# adding the feature
data = data.reshape(len(samples),length, 1)
print(data.shape)

(5000,)
25
(25, 200)
(25, 200, 1)


In [5]:
# import pandas as pd
# import plotly.graph_objects as go
# import pandas as pd
# import geopandas as gpd
# import plotly.express as px
# import matplotlib.pyplot as plt

# path = "/home/adzavon/Documents/MSC_Data_Analysis/conflicts/let_stry.csv"
# conflicts_dataset = pd.read_csv(path,index_col=0,dtype = {"ccaa_id": str}, encoding = 'latin-1')
# geojson_map = gpd.read_file("/home/adzavon/Documents/MSC_Data_Analysis/study area maping/regions.geojson")
# shapefile = gpd.read_file("/home/adzavon/Documents/MSC_Data_Analysis/study area maping/gadm36_BFA_shp/gadm36_BFA_shp/gadm36_BFA_1.shp")
# shapefile_map = shapefile[["NAME_1","geometry"]]
# merged = shapefile.set_index('NAME_1').join(conflicts_dataset.set_index("Region"))
# #merged_file = merged[["Year","EVENT_TYPE","SUM_CONFLICTS","geometry"]]
# #merged.head(2)
# #merged_file
# merged

In [6]:
# # conflicts_dataset.groupby(["Year","Region","EVENT_TYPE"]).sum()

# fig, ax = plt.subplots(1, figsize=(10,6))
# merged_file.plot(column='SUM_CONFLICTS', cmap='Blues', linewidth=1, ax=ax, edgecolor='0.9', legend = True)
# ax.axis('off')

In [7]:
# fig = px.choropleth(merged_file, geojson=merged.geometry, 
#                     locations=merged_file.index, color="SUM_CONFLICTS",
#                     height=500,
#                    color_continuous_scale="Viridis")
# # fig.update_geos(fitbounds="locations", visible=True)
# # fig.update_layout(
# #     title_text='Map'
# #)
# # fig.update(layout = dict(title=dict(x=0.5)))
# # fig.update_layout(
# #     margin={"r":0,"t":30,"l":10,"b":10},
# #     coloraxis_colorbar={
# #         'title':'Sum'})
# fig.show()

# Univariate MLP Models

Data Preparation

In [8]:
from numpy import array

def split_sequence(sequence, n_steps):
    x,y = list(),list()
    for i in range(len(sequence)):
        end_ix = i + n_steps
        if end_ix > len(sequence)-1:
            break
        seq_x,seq_y = sequence[i:end_ix] , sequence[end_ix]
        x.append(seq_x)
        y.append(seq_y)
    return array(x), array(y)

raw_seq = [10,20,30,40,50,60,70,80,90,100]
n_steps = 3
x,y = split_sequence(raw_seq,n_steps)
for i in range(len(x)):
    print(x[i],y[i])

[10 20 30] 40
[20 30 40] 50
[30 40 50] 60
[40 50 60] 70
[50 60 70] 80
[60 70 80] 90
[70 80 90] 100


# MLP Model

In [9]:
# define model

from keras.models import Sequential
from keras.layers import Dense
model = Sequential()
model.add(Dense(100, activation = "relu", input_dim = n_steps))
model.add(Dense(1))
model.compile(optimizer='adam',loss="mse")

# fit the model

model.fit(x,y, epochs=2000,verbose=0)

# demonstrate a prediction

x_input = array([70,80,90])
x_input = x_input.reshape((1,n_steps))
y_hat = model.predict(x_input,verbose=0)
y_hat

2023-03-06 09:21:49.721790: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-03-06 09:21:49.831242: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-03-06 09:21:49.834717: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: :/usr/local/lib
2023-03-06 09:21:49.834728: I tensorflow/stream_executor/cuda/cudart_stub.cc:29]

array([[100.2191]], dtype=float32)

# Multivariate MLP Models

# 1 - Multivariate MLP Models

In [10]:


# deffine the input seq

in_seq1 = array([10,20,30,40,50,60,70,80,90])
in_seq2 = array([15,25,35,45,55,65,75,85,95])
out_seq = array([in_seq1[i] + in_seq2[i] for i in range(len(in_seq1))])

In [11]:
# cenvert to [row, columns] structure 

from numpy import array
from numpy import hstack


in_seq1 = in_seq1.reshape(len(in_seq1),1)
in_seq2 = in_seq2.reshape(len(in_seq2),1)
out_seq = out_seq.reshape(len(out_seq),1)

# make it horizontal stack column

dataset = hstack((in_seq1,in_seq2,out_seq))

print(dataset)

[[ 10  15  25]
 [ 20  25  45]
 [ 30  35  65]
 [ 40  45  85]
 [ 50  55 105]
 [ 60  65 125]
 [ 70  75 145]
 [ 80  85 165]
 [ 90  95 185]]


In [12]:
# multivariate sequence into samples

def split_sequence(sequence,n_steps):
    x, y = list(), list()
    for i in range(len(sequence)):
        end_x = i + n_steps
        
        if end_x > len(sequence):
            break
        seq_x, seq_y = sequence[i:end_x, :-1], sequence[end_x-1,-1]
        x.append(seq_x)
        y.append(seq_y)
    return array(x), array(y)

dataset = hstack((in_seq1,in_seq2,out_seq))
n_steps = 3
print(x.shape,y.shape)
x,y = split_sequence(dataset, n_steps)
for i in range(len(y)):
    print(x[i],y[i])


(7, 3) (7,)
[[10 15]
 [20 25]
 [30 35]] 65
[[20 25]
 [30 35]
 [40 45]] 85
[[30 35]
 [40 45]
 [50 55]] 105
[[40 45]
 [50 55]
 [60 65]] 125
[[50 55]
 [60 65]
 [70 75]] 145
[[60 65]
 [70 75]
 [80 85]] 165
[[70 75]
 [80 85]
 [90 95]] 185


In [13]:
# flatten the input 

n_input = x.shape[1] * x.shape[2]
x = x.reshape(x.shape[0],n_input)

In [14]:
# define the moel

from keras.models import Sequential
from keras.layers import Dense

model = Sequential()
model.add(Dense(100, activation = "relu", input_dim = n_input))
model.add(Dense(1))
model.compile(optimizer='adam',loss="mse")

In [15]:
# fit the moedl
model.fit(x,y, epochs=2000,verbose=0)


# demonstrate the prediction

x_input = array([[80,85],[90,95],[100,105]])
x_input = x_input.reshape(1,n_input)
y_hat = model.predict(x_input,verbose=0)
y_hat

array([[206.31926]], dtype=float32)

Multi-headed MLP Model                                                                                                                   

There is another more elaborate way to model the problem. Each input series can be handled by
a separate MLP and the output of each of these submodels can be combined before a prediction
is made for the output sequence. We can refer to this as a multi-headed input MLP model. It
may offer more flexibility or better performance depending on the specifics of the problem that
are being modeled. This type of model can be defined in Keras using the Keras functional API.
First, we can define the first input model as an MLP with an input layer that expects vectors
with n steps features.

In [16]:
from numpy import array
from numpy import hstack
from keras.layers import Input
from keras.layers import concatenate
from keras.models import Model
from keras.layers import Dense

def split_sequence(sequence,n_steps):
    x,y = list(),list()
    for i in range(len(sequence)):
        end_x = i + n_steps
        if end_x > len(sequence):
            break
        seq_x, seq_y = sequence[i:end_x,:-1], sequence[end_x-1,-1]
        x.append(seq_x)
        y.append(seq_y)
    return array(x), array(y)

# define input sequenceabs

in_seq1 = array([10,20,30,40,50,60,70,80,90])
in_seq2 = array([15,25,35,45,55,65,75,85,95])
out_seq = array([in_seq1[i] + in_seq2[i] 
                 for i in range(len(in_seq1))])

# convert to [row,columns] structure
in_seq1 = in_seq1.reshape(len(in_seq1),1)
in_seq2 = in_seq2.reshape(len(in_seq2),1)
out_seq = out_seq.reshape(len(out_seq),1)

#horizontal stack column

dataset = hstack((in_seq1,in_seq2,out_seq))

# number of time steps
n_steps = 3

# convert into input output
x,y = split_sequence(dataset,n_steps)

# #separate input data
x1 = x[:,:,0]
x2 = x[:,:,1]

# first input model
# first input model
visible1 = Input(shape=(n_steps,))
dense1 = Dense(100, activation='relu')(visible1)
# second input model
visible2 = Input(shape=(n_steps,))
dense2 = Dense(100, activation='relu')(visible2)
# merge input models
merge = concatenate([dense1, dense2])
output = Dense(1)(merge)
model = Model(inputs=[visible1, visible2], outputs=output)
model.compile(optimizer='adam', loss='mse')
# fit model
model.fit([x1, x2], y, epochs=2000, verbose=0)
# demonstrate prediction
x_input = array([[80, 85], [90, 95], [100, 105]])
x1 = x_input[:, 0].reshape((1, n_steps))
x2 = x_input[:, 1].reshape((1, n_steps))
yhat = model.predict([x1, x2], verbose=0)
print(yhat)

[[205.8012]]


# 2 - Multiple Parallel Series

In [17]:
from numpy import array
from numpy import hstack
from keras.layers import Input
from keras.layers import concatenate
from keras.models import Model
from keras.layers import Dense
from keras.models import Sequential

def split_sequence(sequence,n_steps):
    x,y = list(),list()
    for i in range(len(sequence)):
        end_x = i + n_steps
        if end_x > len(sequence)-1:
            break
        seq_x, seq_y = sequence[i:end_x,:], sequence[end_x,:]
        x.append(seq_x)
        y.append(seq_y)
    return array(x), array(y)

# define input sequenceabs

in_seq1 = array([10,20,30,40,50,60,70,80,90])
in_seq2 = array([15,25,35,45,55,65,75,85,95])
out_seq = array([in_seq1[i] + in_seq2[i] 
                 for i in range(len(in_seq1))])

# convert to [row,columns] structure
in_seq1 = in_seq1.reshape(len(in_seq1),1)
in_seq2 = in_seq2.reshape(len(in_seq2),1)
out_seq = out_seq.reshape(len(out_seq),1)

#horizontal stack column

dataset = hstack((in_seq1,in_seq2,out_seq))

# number of time steps
n_steps = 3

# convert into input output
x,y = split_sequence(dataset,n_steps)

print(x.shape,y.shape)

# summarizing the data
for i in range(len(x)):
    print(x[i],y[i])

(6, 3, 3) (6, 3)
[[10 15 25]
 [20 25 45]
 [30 35 65]] [40 45 85]
[[20 25 45]
 [30 35 65]
 [40 45 85]] [ 50  55 105]
[[ 30  35  65]
 [ 40  45  85]
 [ 50  55 105]] [ 60  65 125]
[[ 40  45  85]
 [ 50  55 105]
 [ 60  65 125]] [ 70  75 145]
[[ 50  55 105]
 [ 60  65 125]
 [ 70  75 145]] [ 80  85 165]
[[ 60  65 125]
 [ 70  75 145]
 [ 80  85 165]] [ 90  95 185]


In [18]:
# flatten input
n_input = x.shape[1] * x.shape[2]
x = x.reshape((x.shape[0],n_input))

In [19]:
n_output = y.shape[1]

In [20]:
# define model

model = Sequential()
model.add(Dense(100, activation="relu",input_dim = n_input))
model.add(Dense(n_output))
model.compile(optimizer="adam",loss="mse")

In [21]:
# fit the model

model.fit(x,y,epochs=200,verbose=0)

In [22]:
# demonstrate prediction

x_input = array([[70,75,145], [80,85,165], [90,95,185]])
x_input = x_input.reshape((1, n_input))
yhat = model.predict(x_input, verbose=0)
print(yhat)

[[106.74658 115.66115 220.84004]]


Multi-output MLP Model


As with multiple input series, there is another, more elaborate way to model the problem. Each
output series can be handled by a separate output MLP model. We can refer to this as a
multi-output MLP model. It may offer more flexibility or better performance depending on the
specifics of the problem that is being modeled. This type of model can be defined in Keras
using the Keras functional API. First, we can define the input model as an MLP with an input
layer that expects flattened feature vectors.

In [23]:
# multivariate output mlp example
from numpy import array
from numpy import hstack
from keras.models import Model
from keras.layers import Input
from keras.layers import Dense
# split a multivariate sequence into samples
def split_sequences(sequences, n_steps):
    x, y = list(), list()
    for i in range(len(sequences)):
        # find the end of this pattern
        end_ix = i + n_steps
        # check if we are beyond the dataset
        if end_ix > len(sequences)-1:
            break
        # gather input and output parts of the pattern
        seq_x, seq_y = sequences[i:end_ix, :], sequences[end_ix, :]
        x.append(seq_x)
        y.append(seq_y)
    return array(x), array(y)
# define input sequence
in_seq1 = array([10, 20, 30, 40, 50, 60, 70, 80, 90])
in_seq2 = array([15, 25, 35, 45, 55, 65, 75, 85, 95])
out_seq = array([in_seq1[i]+in_seq2[i] for i in range(len(in_seq1))])
# convert to [rows, columns] structure
in_seq1 = in_seq1.reshape((len(in_seq1), 1))
in_seq2 = in_seq2.reshape((len(in_seq2), 1))
out_seq = out_seq.reshape((len(out_seq), 1))
# horizontally stack columns
dataset = hstack((in_seq1, in_seq2, out_seq))
# choose a number of time steps
n_steps = 3
# convert into input/output
x, y = split_sequences(dataset, n_steps)
# flatten input
n_input = x.shape[1] * x.shape[2]

In [24]:
x = x.reshape((x.shape[0], n_input))
# separate output
y1 = y[:, 0].reshape((y.shape[0], 1))
y2 = y[:, 1].reshape((y.shape[0], 1))
y3 = y[:, 2].reshape((y.shape[0], 1))
# define model
visible = Input(shape=(n_input,))
dense = Dense(100, activation='relu')(visible)
# define output 1
output1 = Dense(1)(dense)
# define output 2
output2 = Dense(1)(dense)
# define output 2
output3 = Dense(1)(dense)
# tie together
model = Model(inputs=visible, outputs=[output1, output2, output3])
model.compile(optimizer='adam', loss='mse')
# fit model
model.fit(x, [y1,y2,y3], epochs=2000, verbose=0)
# demonstrate prediction
x_input = array([[70,75,145], [80,85,165], [90,95,185]])
x_input = x_input.reshape((1, n_input))
yhat = model.predict(x_input, verbose=0)
print(yhat)

[array([[100.98739]], dtype=float32), array([[105.49902]], dtype=float32), array([[206.69803]], dtype=float32)]


# Multi-step MLP Models

In [25]:
from numpy import array 
from keras.layers import Dense
from keras.models import Sequential


def split_sequence(sequence, n_steps_in, n_steps_out):
    x,y = list(),list()
    for i in range(len(sequence)):
        end_ix = i + n_steps_in
        out_end_ix = end_ix + n_steps_out
        
        if out_end_ix > len(sequence):
            break
        seq_x, seq_y = sequence[i:end_ix] , sequence[end_ix:out_end_ix]
        x.append(seq_x)
        y.append(seq_y)
    return array(x), array(y)

raw_seq = [10,20,30,40,50,60,70,80,90]

n_steps_in, n_steps_out = 3,2

x,y = split_sequence(raw_seq,n_steps_in,n_steps_out)

for i in range(len(x)):
    print(x[i],y[i])

[10 20 30] [40 50]
[20 30 40] [50 60]
[30 40 50] [60 70]
[40 50 60] [70 80]
[50 60 70] [80 90]


In [26]:
# define the model

model = Sequential()
model.add(Dense(100,activation="relu",input_dim = n_steps_in))
model.add(Dense(n_steps_out))
model.compile(optimizer="adam", loss="mse")

In [27]:
# fit the model

model.fit(x,y, epochs=2000, verbose=0)

# demonstrate prediction

x_input = array([70,80,90])
x_input = x_input.reshape(1,n_steps_in)
yhat = model.predict(x_input,verbose=0)

In [28]:
print(yhat)

[[100.392006 110.86723 ]]


# How to Develop CNNs for Time Series Forecasting

# Univariate CNN Models

In [33]:
def split_sequence(sequence,n_steps):
    x,y = list(),list()
    for i in range(len(sequence)):
        end_ix = i + n_steps
        
        if end_ix > len(sequence)-1:
            break
        seq_x, seq_y = sequence[i:end_ix] , sequence[end_ix]
        x.append(seq_x)
        y.append(seq_y)
        
    return array(x), array(y)

sequence = [10,20,30,40,50,60,70,80,90]
n_steps = 3
x,y = split_sequence(sequence,n_steps)
for i in range(len(x)):
    print(x[i],y[i])

[10 20 30] 40
[20 30 40] 50
[30 40 50] 60
[40 50 60] 70
[50 60 70] 80
[60 70 80] 90


In [35]:
# reshape from [samples, timesteps] into [samples, timesteps, features]

n_features = 1
x = x.reshape(x.shape[0],x.shape[1],n_features)

array([[[10],
        [20],
        [30]],

       [[20],
        [30],
        [40]],

       [[30],
        [40],
        [50]],

       [[40],
        [50],
        [60]],

       [[50],
        [60],
        [70]],

       [[60],
        [70],
        [80]]])

In [2]:
# define the model 
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers.convolutional import conv1d
from keras.layers.convolutional import MaxPooling1D
from keras.layers.convolutional import Conv1D

model = Sequential()
# model.add(conv1d(64,2,
#                  activation="relu",
#                  input_shape=(n_steps,n_features)))
# model.add(MaxPooling1D())
model.add(Conv1D(64, 2, activation='relu', input_shape=(n_steps, n_features)))
model.add(Flatten())
model.add(Dense(50,activation="relu"))
model.add(Dense(1))
model.compile(optimizer="adam",loss = "mse")

# model fit

model.fit(x,y,epochs=1000, verbose=0)

# Demonstrate prediction

x_input = array([70,80,90])
x_input = x_input.reshape(1,n_steps,n_features)
y_hat = model.predict(x_input,verbose=0)
print(y_hat)

2023-03-06 11:16:57.679585: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-03-06 11:16:57.765313: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-03-06 11:16:57.768789: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: :/usr/local/lib
2023-03-06 11:16:57.768799: I tensorflow/stream_executor/cuda/cudart_stub.cc:29]

NameError: name 'n_steps' is not defined

# Multivariate CNN Models
Multiple Input Series

In [3]:
from numpy import array
from numpy import hstack


def split_sequence(sequence,n_steps):
    x,y = list(),list()
    for i in range(len(sequence)):
        end_ix = i + n_steps
        if end_ix > len(sequence):
            break
        seq_x, seq_y = sequence[i:end_ix, :-1], sequence[end_ix-1,-1]
        x.append(seq_x)
        y.append(seq_y)
    return array(x),array(y)

in_seq1 = array([10, 20, 30, 40, 50, 60, 70, 80, 90])
in_seq2 = array([15, 25, 35, 45, 55, 65, 75, 85, 95])
out_seq = array([in_seq1[i]+in_seq2[i] for i in range(len(in_seq1))])

# convert to [rows, columns] structure

in_seq1 = in_seq1.reshape(len(in_seq1),1)
in_seq2 = in_seq2.reshape(len(in_seq2),1)
out_seq = out_seq.reshape(len(out_seq),1)
dataset = hstack((in_seq1,in_seq2,out_seq))

# choose a number of time steps
n_steps = 3

# convert into input output

x,y = split_sequence(dataset,n_steps)

for i in range(len(x)):
    print(x[i], y[i])
    
n_features = x.shape[2]

[[10 15]
 [20 25]
 [30 35]] 65
[[20 25]
 [30 35]
 [40 45]] 85
[[30 35]
 [40 45]
 [50 55]] 105
[[40 45]
 [50 55]
 [60 65]] 125
[[50 55]
 [60 65]
 [70 75]] 145
[[60 65]
 [70 75]
 [80 85]] 165
[[70 75]
 [80 85]
 [90 95]] 185


In [4]:
# define model
n_features = x.shape[2]
model.add(Conv1D(64, 2, 
                 activation='relu',
                 input_shape=(n_steps, n_features)))

model.add(MaxPooling1D())
model.add(Flatten())
model.add(Dense(50, activation='relu'))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')
# fit model
model.fit(x, y, epochs=1000, verbose=0)
# demonstrate prediction
x_input = array([[80, 85], [90, 95], [100, 105]])
x_input = x_input.reshape((1, n_steps, n_features))
yhat = model.predict(x_input, verbose=0)
print(yhat)

[[208.58894]]


# Multi-step CNN Models

In [9]:
# univariate multi-step vector-output 1d cnn example
from numpy import array
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers.convolutional import Conv1D
from keras.layers.convolutional import MaxPooling1D
# split a univariate sequence into samples
def split_sequence(sequence, n_steps_in, n_steps_out):
    X, y = list(), list()
    for i in range(len(sequence)):
        # find the end of this pattern
        end_ix = i + n_steps_in
        out_end_ix = end_ix + n_steps_out
        # check if we are beyond the sequence
        if out_end_ix > len(sequence):
            break
    # gather input and output parts of the pattern
    seq_x, seq_y = sequence[i:end_ix], sequence[end_ix:out_end_ix]
    X.append(seq_x)
    y.append(seq_y)
    return array(X), array(y)
# define input sequence
raw_seq = [10, 20, 30, 40, 50, 60, 70, 80, 90]
# choose a number of time steps
n_steps_in, n_steps_out = 3, 2
# split into samples
X, y = split_sequence(raw_seq, n_steps_in, n_steps_out)
# reshape from [samples, timesteps] into [samples, timesteps, features]
# split into samples
X, y = split_sequence(raw_seq, n_steps_in, n_steps_out)
# reshape from [samples, timesteps] into [samples, timesteps, features]
n_features = 1
X = X.reshape((X.shape[0], X.shape[1], n_features))
# define model
model = Sequential()
model.add(Conv1D(64, 2, activation='relu', input_shape=(n_steps_in, n_features)))
model.add(MaxPooling1D())
model.add(Flatten())
model.add(Dense(50, activation='relu'))
model.add(Dense(n_steps_out))
model.compile(optimizer='adam', loss='mse')
# fit model
model.fit(X, y, epochs=2000, verbose=0)
# demonstrate prediction
x_input = array([70, 80, 90])
x_input = x_input.reshape((1, n_steps_in, n_features))
yhat = model.predict(x_input, verbose=0)
print(yhat)

[[101.555916 101.59334 ]]


# How to Develop LSTMs for Time Series Forecasting